- name: Install and configure HAProxy
  hosts: load_balancer
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Start and enable HAProxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started
